In [ ]:
import numpy as np

In [ ]:
#datatype of numpy array
data = np.array([1,2,3,4])
print(data)
type(data)

[1 2 3 4]


numpy.ndarray

#array creation


In [ ]:
#creating a 1D array

data = np.array([1,2,3,4])
print(data)

[1 2 3 4]


In [ ]:
data.shape

(4,)

In [ ]:
#creating a 2D array
data1 = np.array([[1,2,3],[4,5,6]])
print(data1)
data1.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
#specifying datatype
data2 = np.array([[1,2,3],[4,5,6]],dtype=float)
print(data2)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
#creating arrays of zeros

data3 = np.zeros((3,2))
print(data3)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#creating arrays of ones

data4 = np.ones((4,5))
print(data4)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# creating array with a particular value

data5 = np.full((2,4),4)
print(data5)

[[4 4 4 4]
 [4 4 4 4]]


In [ ]:
#creating identity matrix

data6 = np.eye(3)
print(data6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# creating an array with random values (give values b/w 0.0(inclusive) and 1.0(exclusive))

data7 = np.random.random((2,3))
print(data7)

[[0.86582093 0.0754903  0.9149857 ]
 [0.65654624 0.9339242  0.14211435]]


In [ ]:
#creating array with random integer values

data8 = np.random.randint(10,20,(2,3))
print(data8)

[[13 11 19]
 [10 15 15]]


In [ ]:
#creating array of evenly spaced values - no: of values required is specified

data9 = np.linspace(10,20,5)
print(data9)

[10.  12.5 15.  17.5 20. ]


In [ ]:
#creating array of evenly spaced values - step is mentioned

data10 = np.arange(10,20,2)
print(data10)

[10 12 14 16 18]


In [ ]:
#converting a list to numpy array

l = [1,2,3]

data11 = np.asarray(l)
print(data11)
type(data11)

[1 2 3]


numpy.ndarray

#Analyzing array

In [ ]:
a = np.random.randint(1,20,(3,3))
print(a)

[[ 1  3  4]
 [17 17  4]
 [19 11 11]]


In [ ]:
#array dimension
print(a.shape)

(3, 3)


In [ ]:
#no: of dimension
print(a.ndim)

2


In [ ]:
#no: of elements
print(a.size)

9


In [ ]:
#datatype
print(a.dtype)

int64


#Basic mathematical operations


In [ ]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)

[[9 6 6]
 [3 9 4]
 [4 5 6]]
[[4 7 3]
 [9 1 5]
 [1 2 4]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a@b)

[[13 13  9]
 [12 10  9]
 [ 5  7 10]]
[[ 5 -1  3]
 [-6  8 -1]
 [ 3  3  2]]
[[36 42 18]
 [27  9 20]
 [ 4 10 24]]
[[2.25       0.85714286 2.        ]
 [0.33333333 9.         0.8       ]
 [4.         2.5        1.5       ]]
[[96 81 81]
 [97 38 70]
 [67 45 61]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.dot(a,b))

[[13 13  9]
 [12 10  9]
 [ 5  7 10]]
[[ 5 -1  3]
 [-6  8 -1]
 [ 3  3  2]]
[[36 42 18]
 [27  9 20]
 [ 4 10 24]]
[[2.25       0.85714286 2.        ]
 [0.33333333 9.         0.8       ]
 [4.         2.5        1.5       ]]
[[96 81 81]
 [97 38 70]
 [67 45 61]]


In [ ]:
# Transpose

a = np.random.randint(1,10,(2,3))
print(a)

[[5 2 2]
 [7 2 8]]


In [ ]:
t = np.transpose(a)
print(t)

# or

t = a.T
print(t)

[[5 7]
 [2 2]
 [2 8]]
[[5 7]
 [2 2]
 [2 8]]


In [ ]:
#reshaping array
a = np.random.randint(1,10,(2,3))
print(a)
print(a.shape)

[[8 7 2]
 [4 8 1]]
(2, 3)


In [ ]:
b = a.reshape((3,2))
print(b)

[[8 7]
 [2 4]
 [8 1]]


#Basic NumPy functions

In [ ]:
arr = np.array([[10,20,30],[40,50,60]])

In [ ]:
#mean

print(np.mean(arr))

#columnwise mean

print(np.mean(arr,axis=0))

#rowwise mean

print(np.mean(arr,axis=1))

35.0
[25. 35. 45.]
[20. 50.]


In [ ]:
#max

print(np.max(arr))

#columnwise max

print(np.max(arr,axis=0))

#rowwise max

print(np.max(arr,axis=1))

60
[40 50 60]
[30 60]


In [ ]:
#min

print(np.min(arr))

#columnwise min

print(np.min(arr,axis=0))

#rowwise min

print(np.min(arr,axis=1))

10
[10 20 30]
[10 40]


In [ ]:
#sum

print(np.sum(arr))

#columwise

print(np.sum(arr,axis=0))

#rowwise

print(np.sum(arr,axis=1))

210
[50 70 90]
[ 60 150]


In [ ]:
#median

print(np.median(arr))

#columnwise

print(np.median(arr,axis=0))

#rowwise

print(np.median(arr,axis=1))

35.0
[25. 35. 45.]
[20. 50.]


In [ ]:
#standard deviation

# This treats all values as a single list:
# [10,20,30,40,50,60]

# 1.Mean
# (10+20+30+40+50+60)/6=210/6=35
# 2.Squared differences
# (10 - 35)² = 625
# (20 - 35)² = 225
# (30 - 35)² = 25
# (40 - 35)² = 25
# (50 - 35)² = 225
# (60 - 35)² = 625
# Sum = 1750
# 3.Variance
# 1750/6≈291.67
# 4.Standard deviation
# √291.67 = 17.08

print(np.std(arr))

17.07825127659933


#Indexing and slicing


In [ ]:
# indexing - accessing a specific element using its position

#1D

arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[2])
print(arr[-1])

#2D

arr = np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[1,2])

1
3
5
2
6


In [ ]:
#slicing - getting a range of elements

#1D
arr = np.array([10,20,30,40,50])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

#2D
arr = np.array([[1,2,3],[4,5,6]])
print(arr[:,1])
print(arr[0,:])
print(arr[0:2,1:3])

[20 30 40]
[10 20 30]
[10 30 50]
[2 5]
[1 2 3]
[[2 3]
 [5 6]]


In [ ]:
# Boolean Indexing - filtering elements using condition

#1D
arr = np.array([10,20,30,40,50])
print(arr[arr>25])

arr = np.array([1,2,3,4,5,6])
print(arr[arr%2==0])

#2D
arr = np.array([[1,2,3],[4,5,6]])
print(arr[arr>3])

[30 40 50]
[2 4 6]
[4 5 6]


#mini project

#using 1D

# mark = 45,67,82,90,55,73
# 1. create marks array
# 2. find avg marks
# 3. find students with mark>75(top students)
# 4.count of top students
# 5.students who have marks above avg


#using 2D
# student math  science English
# s1      80    75      90
# s2      60    65      70
# s3      85    90      95
# s4      50    55      60

# 1. create a 2d array
# 2. find avg marks of all students
# 3.find avg mark of each students
# 4. find avg mark of each subject
# 5. find highest mark in each subject



In [ ]:
#1D

#1
marks = np.array([45,67,82,90,55,73])
print(marks)

#2
avg = marks.mean()
print(avg)

#3
top = marks[marks > 75]
print(top)

#4
print(top.size)

#5
print(marks[marks > avg])

NameError: name 'np' is not defined

In [ ]:
#2D

#1
mark = np.array([
    [80,75,90],
    [60,65,70],
    [85,90,95],
    [50,55,60]
])
print(mark)

#2
print(mark.mean())

#3
print(mark.mean(axis=1))

#4
print(mark.mean(axis=0))

#5
print(mark.max(axis=0))



NameError: name 'np' is not defined