In [7]:
#task 1 
import numpy as np

array_practise = np.arange(1,17).reshape(4,4)
print(array_practise)
print(array_practise[0:2,0:2])
print()

b = np.arange(1,16).reshape(3,5)
print(b)
print(b[0,0:5])
print(b[0:3,0])
print(b[0:3,1:4])
print()

c = np.arange(1,26).reshape(5,5)
print(c)
print(c[1:4,1:4])
print()

d = np.arange(1, 17).reshape(4, 4)
even_rows = d[::2]
odd_rows = d[1::2]
print(d)
print(even_rows)
print(odd_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[1 2]
 [5 6]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[1 2 3 4 5]
[ 1  6 11]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [13 14 15 16]]


In [ ]:
##boolean indexing

## Mini Project

In [ ]:
#task 1
marks = np.array([45,67,82,90,55,73])

avg = marks.mean()

top = marks[marks > 75]

count = top.count()




68.66666666666667
[82 90]


NameError: name 'top' is not defined